apiVersion: v1 
kind: ConfigMap 
metadata: 
      name: payment 
      namespace: roboshop 
      labels: 
         component: rabbitmq 
         project: roboshop 
         tier: app 
data: 
   CART_HOST: "cart" 
   CART_PORT: "8080" 
   USER_HOST: "user" 
   USER_PORT: "8080" 
   AMQP_HOST: "rabbitmq" 
--- 
apiVersion: v1 
kind: Secret 
metadata: 
      name: payment
      labels: 
           component: rabbitmq 
           project: roboshop 
           tier: app 
type: Opaque 
data: 
   AMQP_USER: "cm9ib3Nob3A=" 
   AMQP_PASS: "cm9ib3Nob3AxMjM="       
--- 

apiVersion: apps/v1 
kind: Deployment 
metadata: 
      name: payment 
      namespace: roboshop 
      # deployment labels 
      labels: 
         component: payment
         project: roboshop 
         tier: app 
spec: 
   replicas: 1 
   # these are the labels replica set use to create pod replicas, this should match pod labels 
   selector: 
       matchLabels: 
          component: payment 
          project: roboshop 
          tier: app 
   # this is pod definition 
   template: 
      metadata: 
           labels: 
              component: payment 
              project: roboshop 
              tier: app 
      spec: 
        containers: 
        - name: payment 
          image: subbu2/payment:v1 
          resource: 
              requests: 
                 cpu: "50m" 
                 memory: "128Mi" 
              limits: 
                 cpu: "100m"
                 memory: "256Mi" 
          envFrom: 
          - configMapRef: 
              name: payment 
          - secretRef: 
              name: payment
--- 

apiVersion: v1 
kind: Service 
metadata: 
      name: payment 
      namespace: roboshop 
      labels: 
         component: payment 
         project: roboshop 
         tier: app 
spec: 
   selector: 
      component: payment 
      project: roboshop 
      tier: app 
   ports: 
   - protocol: TCP 
     port: 8080 # service port 
     targetPort: 8080 # container port 
--- 

apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata: 
       name: payment 
       namespace: roboshop 
spec: 
    scaleTargetRef: 
        apiVersion: apps/v1 
        kind: Deployment 
        name: payment 
    minReplicas: 1 
    maxReplicas: 10 
    metrics: 
    - type: Resource 
      resource: 
         name: cpu 
         target: 
            type: Utilization
            averageUtilization: 10    