apiVersion: storage.k8s.io/v1 
kind: StorageClass
metadata: 
    name: roboshop-ebs 
provisioner: ebs.csi.aws.com 
reclaimPolicy: Retain 
VolumeBindingMode: WaitForFirstConsumer # disk will be create when pod is getting created 
      