apiVersion: v1 
kind: Service
metadata: 
     name: mongodb-headless
     namespace: roboshop 
     labels: 
        component: mongodb 
        project: roboshop 
        tier: database 
spec: 
   clusterIP: None 
   selector: 
       component: mongodb
       project: roboshop 
       tier: database 
   ports: 
   - protocol: TCP 
     port: 27017 #service port 
     targetPort: 27017 #container port  
--- 
apiVersion: v1 
kind: Service 
metadata: 
     name: mongodb 
     namespace: roboshop 
     labels: 
        component: mongodb 
        project: roboshop 
        tier: database 
spec: 
   selector: 
      component: mongodb
      project: roboshop 
      tier: database 
   ports: 
   - protocol: TCP 
     port: 27017 #service port  
     targetPort: 27017 #container port 
--- 
apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
     name: mongodb 
     namespace: roboshop 
     labels: 
       component: mongodb 
       project: roboshop 
       tier: database 
spec: 
   replicas: 2 # by default it will be 1 
   selector: 
       matchlabels: 
           component: mongodb 
           project: roboshop 
           tier: database 
   serviceName: "mongodb-headless" # this should be the headless service 
   # This is pod definition 
   template: 
      metadata: 
         labels: 
            component: mongodb 
            project: roboshop 
            tier: database                                                
      spec: 
        containers: 
        - name: mongodb 
          image: subbu2/mongodb:v1 
          volumeMounts: 
          - name: mongodb-data 
            mountPath: data/db  
   # This is nothing but PVC you can directly create here  or else create seperately 
   volumeClaimTemplates: 
   - metadata: 
       name: mongodb-data 
   spec: 
      accessModes: ["ReadWriteOnce"] 
      storageClassName: "roboshop-ebs" 
      resources:  
         requests: 
            storage: 2Gi                
             

apiVersion: v1 
kind: Service
metadata: 
    name: mongodb-headless 
    namespace: robsohop 
    labels: 
       project: roboshop 
       env: dev 
spec: 
   clusterIP: None 
   selctor: 
     project: roboshop 
     env: dev 
   ports: 
    protocol: TCP 
    port: 27017 
    targetPort: 27017 

apiVersion: v1 
kind: Service
metadata: 
    name: mongodb-headless 
    namespace: robsohop 
    labels: 
       project: roboshop 
       env: dev 
spec:  
   selctor: 
     project: roboshop 
     env: dev 
   ports: 
    protocol: TCP 
    port: 27017 
    targetPort: 27017 
    
apiVersion: v1  
kind: StatefulSet 
metadata: 
    name: mongodb 
    namespace: roboshop 
    labels:  
       project: roboshop 
       env: dev 
spec:  
   replicas: 2 
   serviceNmae: mongodb-svc-headless 
   selector: 
      matchLabels: 
          project: roboshop 
          env: dev 
   template: 
      metadata: 
         labels: 
            project: roboshop 
            env: dev 
      spec: 
        containers: 
           name: mongodb 
           image: subbu2/mongodb:v1 
           volumeMounts: 
            name: www
            mountPath: data/db 
      volumeClaimTemplates: 
      - metadata: 
           nmae: www 
        spec: 
          accessModes: ["ReadWriteOnce"] 
          storageClassName: "ebs-roboshop" 
          resources: 
             requests: 
                storage: 2Gi 